name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt

    - name: Lint with ruff
      run: |
        ruff check

    - name: Run unittests
      run: |
        python -m unittest discover -s tests

    - name: Generate coverage report
      run: |
        coverage run -m unittest discover -s tests
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # only needed for private repos
        files: ./coverage.xml
        fail_ci_if_error: true
 
